site_name: Spartan Documentation
pages:
    - Home: index.md
    - Status: status.md
    - Getting Started: getting_started.md
    - Managing Data: managing_data.md
    - Software: software.md
    - GPGPU: gpu.md
    - FAQ: faq.md
    - _Edward Transition: edward_transition.md
theme_dir: uom_theme
google_analytics: ['UA-97236408-1', 'auto']
